name: release

on:
  release:
    types:
      - created
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup eli
        uses: alis-is/setup-eli@v1
        with:
          prerelease: true

      - name: inject version
        run: |
          eli .github/inject_version.lua ${{ github.ref_name }}

      - name: test ami
        run: |
          eli ./tests/all.lua

      - name: build ami
        run: |
          export ELI_PATH=$PWD/eli
          eli ./build/build.lua
          cd .meta && zip ../meta.zip -r * && cd ..

      - name: prepare assets
        run: |
          mkdir -p upload
          mv bin/ami.lua upload/ami.lua
          mv bin/exit-codes.json upload/exit-codes.json
          mv meta.zip upload/meta.zip

      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.4.0
        with:
          file_glob: true
          tag: ${{ github.ref }}
          file: upload/*