name: release

on:
  release:
    types:
      - created
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup eli
        uses: alis-is/setup-eli@v1

      - name: inject version
        run: |
          eli .github/inject_version.lua ${{ github.ref_name }}

      - name: test ami
        run: |
          eli ./tests/all.lua

      - name: build ami
        run: |
          export ELI_PATH=$PWD/eli
          eli ./build/build.lua
          cd .meta && zip ../meta.zip -r * && cd ..

      - name: publish
        uses: ncipollo/release-action@v1
        with:
          artifacts: "meta.zip,bin/ami.lua,bin/exit-codes.json"
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}