name: test

on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup eli
        uses: alis-is/setup-eli@v1
        with:
          prerelease: true
          eli-version: '0.36.0-alpha.1'

      - name: inject version
        run: |
          eli .github/inject_version.lua ${{ github.ref_name }}

      - name: test ami
        run: |
          eli ./tests/all.lua